### ISSUE TITLE
Fails to build with latest atools 4.0.5

### ISSUE THREAD

**Issue by merspieler** [slawekmikula/littlefgconnect#3]
When building against the updated atools, I get the following error messages:
```
../src/mainwindow.cpp: In member function 'void MainWindow::showOfflineHelp()':
../src/mainwindow.cpp:161:16: error: 'openFile' is not a member of 'atools::gui::HelpHandler'
  161 |   HelpHandler::openFile(this, HelpHandler::getHelpFile(HELP_OFFLINE_FILE, "en" /* override */));
      |                ^~~~~~~~
../src/fgconnect.cpp: In member function 'bool xpc::XpConnect::fillSimConnectData(QString, atools::fs::sc::SimConnectData&, bool)':
../src/fgconnect.cpp:180:15: warning: unused variable 'fuelDensityJetA' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
  180 |         float fuelDensityJetA = temperatureFarenheit * -0.00325 + 6.95;
      |               ^~~~~~~~~~~~~~~
make: *** [Makefile:548: mainwindow.o] Error 1
make: *** Waiting for unfinished jobs....
../src/main.cpp: In function 'int main(int, char**)':
../src/main.cpp:85:13: error: 'logSettingsInformation' is not a member of 'atools::settings::Settings'
   85 |   Settings::logSettingsInformation();
      |             ^~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:540: main.o] Error 1
error: builder for '/nix/store/0zcarn79zah6qq3xpdgndbrgfasflg5z-littlefgconnect-0.1.drv' failed with exit code 2;
       last 10 log lines:
       > ../src/fgconnect.cpp:180:15: warning: unused variable 'fuelDensityJetA' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-variable-Wunused-variable8;;]
       >   180 |         float fuelDensityJetA = temperatureFarenheit * -0.00325 + 6.95;
       >       |               ^~~~~~~~~~~~~~~
       > make: *** [Makefile:548: mainwindow.o] Error 1
       > make: *** Waiting for unfinished jobs....
       > ../src/main.cpp: In function 'int main(int, char**)':
       > ../src/main.cpp:85:13: error: 'logSettingsInformation' is not a member of 'atools::settings::Settings'
       >    85 |   Settings::logSettingsInformation();
       >       |             ^~~~~~~~~~~~~~~~~~~~~~
       > make: *** [Makefile:540: main.o] Error 1
```

**Comment by slawekmikula** [comment]
I was looking at the code long time ago. Also changed computer and have to reconfigure whole toolchain. The code is/was compiled against master branch. As far as I remember LittleNavMap have quite divergent branches (release vs master) so maybe this is the case. I'll take a look at it, but first I have to reconfigure the toolchain.

**Comment by slawekmikula** [comment]
I'have checked the code. All of the errors come from the GUI part (didn't check application running with all components - FG/LNM). I won't create additional branch for the 4.0 code (right now) because i've locally created some time ago modifications to visualize online traffic from the mpserver data and it is not finished, but 

in mainwindow.cpp change

`void MainWindow::showOfflineHelp()
{
  HelpHandler::openHelpUrlFile(this, HelpHandler::getHelpFile(HELP_OFFLINE_FILE, "en" /* override */), "en");
}
`

in main.cpp change

`
Application::addReportPath(QObject::tr("Log files:"), LoggingHandler::getLogFiles(false));
`
and

`
Settings::logMessages();
`
instead of 
`

**Comment by merspieler** [comment]
It builds now (did patch out the cpptrace dependency since it didn't seem to be used and wasn't available in nixpkgs)

**Comment by albar965** [comment]
> It builds now (did patch out the cpptrace dependency since it didn't seem to be used and wasn't available in nixpkgs)

Set the environment variable `ATOOLS_NO_CRASHHANDLER` to disable all crash handling stuff. No cpptrace needed if this is set.

Alex
